### ISSUE TITLE
Running `--import-contacts` with v1.1.0 fails

### ISSUE THREAD

**Issue by justinvw** [cert-se/megatron-java#3]
Importing test data by using the `--import-contacts` switch with Megatron v1.1.0 fails:
```
$ ./megatron-dev.sh --import-contacts
Fri Jan 23 11:09:06 UTC 2015: Megatron Starts.
2015-01-23 11:09:06.905 INFO  - Megatron 1.1.0 (2014-11-17 10:27:17) started.
2015-01-23 11:09:08.670 ERROR - No import filename provided
2015-01-23 11:09:08.671 INFO  - Megatron finished.
Fri Jan 23 11:09:08 UTC 2015: Megatron Finished.
```

I think this partly has to do with the introduction of an incorrect return statement in [ImportSystemData.java](https://github.com/cert-se/megatron-java/blob/master/src/se/sitic/megatron/db/ImportSystemData.java#L93) (lines 93-97) that causes the configured ``import.dataFile`` file (``conf/dev/systemdata.txt``) to never be loaded.

Compiling Megatron with this return statement removed allows the importer to successfully add some of the entities in ``systemdata.txt`` (namely ``Priority``, ``EntryType`` and ``JobType``). However, it still crashes when trying to import organizations:
```
2015-01-23 11:23:58.526 ERROR - NoSuchMethodException in setObjectAttributes; (import file line no: 52) : se.sitic.megatron.db.DbManager.addOrganization(se.sitic.megatron.entity.Organization)
java.lang.NoSuchMethodException: se.sitic.megatron.db.DbManager.addOrganization(se.sitic.megatron.entity.Organization)
    at java.lang.Class.getMethod(Class.java:1670)
    at se.sitic.megatron.db.ImportSystemData.setObjectAttributes(ImportSystemData.java:341)
    at se.sitic.megatron.db.ImportSystemData.processDataLine(ImportSystemData.java:192)
    at se.sitic.megatron.db.ImportSystemData.processLine(ImportSystemData.java:131)
    at se.sitic.megatron.db.ImportSystemData.importFile(ImportSystemData.java:107)
    at se.sitic.megatron.db.ImportSystemData.importFile(ImportSystemData.java:87)
    at Megatron.processCommands(Megatron.java:306)
    at Megatron.main(Megatron.java:170)
2015-01-23 11:23:58.532 FATAL - Error: NoSuchMethodException in setObjectAttributes; (import file line no: 52) : se.sitic.megatron.db.DbManager.addOrganization(se.sitic.megatron.entity.Organization)
se.sitic.megatron.core.MegatronException: NoSuchMethodException in setObjectAttributes; (import file line no: 52) : se.sitic.megatron.db.DbManager.addOrganization(se.sitic.megatron.entity.Organization)
    at se.sitic.megatron.db.ImportSystemData.handleException(ImportSystemData.java:496)
    at se.sitic.megatron.db.ImportSystemData.setObjectAttributes(ImportSystemData.java:351)
    at se.sitic.megatron.db.ImportSystemData.processDataLine(ImportSystemData.java:192)
    at se.sitic.megatron.db.ImportSystemData.processLine(ImportSystemData.java:131)
    at se.sitic.megatron.db.ImportSystemData.importFile(ImportSystemData.java:107)
    at se.sitic.megatron.db.ImportSystemData.importFile(ImportSystemData.java:87)
    at Megatron.processCommands(Megatron.java:306)
    at Megatron.main(Megatron.java:170)
```

You can find the complete ``megatron.log`` here: https://gist.github.com/justinvw/8926adc3bd28046869f1

**Comment by nobbyhegel** [comment]
I'm having similar issues. I point it to the /conf/dev/systemdata.txt in the command line but I get a further error saying I need to specify a job-type. I try and pick a relevant job type but this just give a further error. Any clarification would be welcome.
